- name: Play1  
  hosts: all                        # groupName in the inventory file 
  vars:
    URL: play.google.com
  vars_prompt:
    - name: URNAME
      prompt: enter the name
      private: false

  vars_files: 
     - "{{ENV}}.yml"
  tasks: 
    - name: Printing Hai from task1 of play1
      ansible.builtin.debug:
        msg: "printing the message {{URL}}"
      
     
    - name: Printing prompt variable  
      ansible.builtin.debug:
        msg: Name of the person is {{URNAME}}

    
- name: Play2  
  hosts: all                      # groupName in the inventory file 
  vars:
    URL: curl.googel.com
  tasks: 
    - name: Printing Hai from task1 of play2
      ansible.builtin.debug:
        msg: "printing the message {{URL}}"

    - name: This is env specific
      ansible.builtin.debug:
        msg: Type Of Instance To Be Used {{INS_TYPE}}

     