- name: Play1  
  hosts: all                        # groupName in the inventory file 
  vars:
    URL: play.google.com
  tasks: 
    - name: Printing Hai from task1 of play1
      ansible.builtin.debug:
        msg: "printing the message {{URL}}"

    
- name: Play2  
  hosts: all                      # groupName in the inventory file 
  vars:
    URL: curl.googel.com
  tasks: 
    - name: Printing Hai from task1 of play2
      ansible.builtin.debug:
        msg: "Olaaaaaaaaaaaaaa : task1 from play2"