- name: Demo on facts
  hosts: all
          
  tasks: 
    - name: demo for shell 
      ansible.builtin.shell: uptime
      register: OUT
        

    - name: Printing the mac address
      ansible.builtin.debug:
        msg: printing the shell output "{{OUT}}"