- name: Installing Mavaen for {{COMPONENT}}-{{ENV}}
  ansible.builtin.package:
      name: maven  
      state: present

- name: creating app user
  ansible.builtin.include_role:
    name: common
    tasks_from: create_user

- name: downloading and extracting {{COMPONENT}}
  ansible.builtin.include_role:
    name: common
    tasks_from: download_and_extract

- name: generating the artifacts with NPM
  ansible.builtin.shell: mvn clean package && mv target/{{COMPONENT}}-1.0.jar {{COMPONENT}}.jar
  args:
    chdir: /home/{{APPUSER}}/{{COMPONENT}}/

- name: copying and configuring the {{COMPONENT}} service
  ansible.builtin.include_role:
    name: common
    tasks_from: config_service