- name: Demo on loops
  hosts: all
  tasks:
    - name: Printing the user details 
      ansible.builtin.debug:  
        msg: "value of item {{item}}"
      loop:
        - 300
        - 700
        - 100